name: C mcb32tools CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color
    steps:
      - uses: actions/checkout@v3
      - name: install deps
        run: sudo apt-get install bzip2 make libftdi-dev curl -y
      - name: download mcb32tools
        run: curl -L -O https://github.com/is1200-example-projects/mcb32tools/releases/download/v2.2/mcb32tools-v2.2-x86_64-linux-gnu.run
      - name: install mcb32tools
        run: chmod +x mcb32tools-v2.2-x86_64-linux-gnu.run && sudo ./mcb32tools-v2.2-x86_64-linux-gnu.run
      - name: make
        run: source /opt/mcb32tools/environment && cd src && make
